name: TPASystem
version: 1.2
main: com.tpasystem.TPASystem
api-version: 1.21
commands:
  tpa:
    description: 다른 플레이어에게 텔레포트 요청을 보냅니다.
    usage: /tpa <player>
    permission: tpasystem.tpa
  tpaccept:
    description: 받은 텔레포트 요청을 수락합니다.
    usage: /tpaccept <player>
    permission: tpasystem.tpaccept
  tpdeny:
    description: 받은 텔레포트 요청을 거절합니다.
    usage: /tpdeny <player>
    permission: tpasystem.tpdeny
  tpcancel:
    description: 보낸 텔레포트 요청을 취소합니다.
    usage: /tpcancel
    permission: tpasystem.tpcancel
permissions:
  tpasystem.tpa:
    description: /tpa 명령어 사용 권한
    default: true
  tpasystem.tpaccept:
    description: /tpaccept 명령어 사용 권한
    default: true
  tpasystem.tpdeny:
    description: /tpdeny 명령어 사용 권한
    default: true
  tpasystem.tpcancel:
    description: /tpcancel 명령어 사용 권한
    default: true
